// const mongoose = require('mongoose');

// const DocumentSchema = new mongoose.Schema({
//     // Reference to the User who owns this document
//     user: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'User',
//         required: true
//     },
//     title: {
//         type: String,
//         required: true,
//         trim: true
//     },
//     fileName: {
//         type: String,
//         required: true
//     },
//     // The secure URL provided by Cloudinary
//     fileUrl: {
//         type: String, 
//         required: true
//     },
//     // The public_id from Cloudinary (needed for deleting the file later)
//     cloudinaryId: {
//         type: String,
//         required: true
//     },
//     /**
//      * Full text extracted from PDF for Gemini AI analysis.
//      * CHANGED: required is set to false to support background processing.
//      */
//     extractedText: {
//         type: String,
//         required: false,
//         default: ""
//     },
//     fileSize: {
//         type: Number, // In bytes
//         required: true
//     },
//     pageCount: {
//         type: Number,
//         default: 0
//     },
//     /**
//      * NEW: Track the processing state of the PDF.
//      * Useful for showing a loading spinner on the frontend card.
//      */
//     status: {
//         type: String,
//         enum: ['processing', 'completed', 'failed'],
//         default: 'processing'
//     },
//     createdAt: {
//         type: Date,
//         default: Date.now
//     }
// });

// // Create an index on the user field for faster retrieval
// DocumentSchema.index({ user: 1 });

// module.exports = mongoose.model('Document', DocumentSchema);

// -------------------------------------------------------------------------------------------------------------

const mongoose = require('mongoose');

const DocumentSchema = new mongoose.Schema({
    // Reference to the User who owns this document
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    title: {
        type: String,
        required: true,
        trim: true
    },
    fileName: {
        type: String,
        required: true
    },
    // The secure URL provided by Cloudinary
    fileUrl: {
        type: String, 
        required: true
    },
    // The public_id from Cloudinary (needed for deleting the file later)
    cloudinaryId: {
        type: String,
        required: true
    },
    /**
     * Full text extracted from PDF for Gemini AI analysis.
     * required is set to false to support background processing.
     */
    extractedText: {
        type: String,
        required: false,
        default: ""
    },
    /**
     * NEW: Persisted AI Summary
     * Stores the 15-20 bullet points generated by Gemini.
     * This saves tokens by preventing re-generation on every click.
     */
    autoSummary: {
        type: String,
        required: false,
        default: ""
    },
    fileSize: {
        type: Number, // In bytes
        required: true
    },
    pageCount: {
        type: Number,
        default: 0
    },
    /**
     * Track the processing state of the PDF.
     * Useful for showing a loading spinner on the frontend card.
     */
    status: {
        type: String,
        enum: ['processing', 'completed', 'failed'],
        default: 'processing'
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

// Create an index on the user field for faster retrieval
DocumentSchema.index({ user: 1 });

module.exports = mongoose.model('Document', DocumentSchema);